name = "256t-content-prod"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[r2_buckets]]
binding = "CONTENT_BUCKET"
bucket_name = "hashbin-content-256t-prod"

routes = [
  { pattern = "256t.us/*", zone_name = "256t.us" },
  { pattern = "www.256t.us/*", zone_name = "256t.us" }
]

[vars]
ENVIRONMENT = "production"
